# Generated by Django 3.2.16 on 2023-02-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('area', models.IntegerField()),
                ('currency', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['id'],
            },
        ),
    ]
